### ISSUE TITLE
Drop files button remains highlighted after uploading files

### ISSUE THREAD

**Issue by syed-razi** [myrithok/James#68] opened 2021-03-07 00:37 UTC
### Description:
I uploaded a file and noticed that the drop file button remains highlighted for a few seconds after the file has been uploaded. This does not feel like it should be expected.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Click "Drop files..." button
2. Upload any file

### Actual Result:

Drop files button is highlighted

![image](https://user-images.githubusercontent.com/25377291/110225465-cd16c780-7eb3-11eb-8a79-41ddf4eb1da0.png)

### Expected Result:

Drop files button is not highlighted

**Comment by eaharis** [comment] 2021-04-01 00:11
We are closing this issue as this is working as intended based on the component. When the component is clicked on or the focus is on it, it turns blue, and after the files are selected, the focus returns to the object and turns blue again.

**Closed by eaharis** 2021-04-01 00:11 UTC
